//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_Practice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fish
    {
        public decimal FishId { get; set; }
        public string FishName { get; set; }
        public string FishType { get; set; }
        public decimal FishRate { get; set; }
        public decimal FishQuantity { get; set; }
    }
}
