//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_Practice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FishSeed
    {
        public decimal FishSeedId { get; set; }
        public string FishSeedName { get; set; }
        public string FishSeedType { get; set; }
        public decimal FishSeedRate { get; set; }
        public decimal FishSeedQuantity { get; set; }
    }
}
