//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_Practice.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MvcCRUDDBEntities1 : DbContext
    {
        public MvcCRUDDBEntities1()
            : base("name=MvcCRUDDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Fish> Fish { get; set; }
        public virtual DbSet<FishSeed> FishSeeds { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblCustomer> tblCustomer { get; set; }
    
        public virtual ObjectResult<USP_GetCustomerList_Result> USP_GetCustomerList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_GetCustomerList_Result>("USP_GetCustomerList");
        }
    }
}
