//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_Practice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomer
    {
        public decimal CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEmail { get; set; }
        public Nullable<decimal> CustomerPhone { get; set; }
        public string CustomerPassword { get; set; }
        public string CustomerAddress { get; set; }
        public Nullable<System.DateTime> AddedDateTime { get; set; }
        public Nullable<decimal> AddedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public Nullable<decimal> UpdatedBy { get; set; }
        public Nullable<decimal> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDateTime { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
